version: '3'
services:
  web:
    container_name: tweet_web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mnt
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
